### PR TITLE
force .elm-thankyou-msg to be visible before fading it out

### PR DESCRIPTION
**Pull request by joernroeder**
this is especially useful if you're displaying the message as tooltip and the element is hidden by default.

```scss
// thank you message as tooltip
.elm-thankyou-msg {
	background: $blue;
	padding: .5rem 1rem .65rem;
	color: #fff;
	display: none;

	&:before {
		position: absolute;
		content: '';
		@include arrowSizing(top, $blue, 0.5rem);
	}
}
```

### CODE REVIEW

**Comment by dominykasgel** [comment]
Thank you for your time! We'll take a look.

**Comment by joernroeder** [comment]
@dominykasgel you're welcome! i've merged the branches into my master branch and therefore removed the feature-branches. I also did some other changes and fixes all over the place. feel free to open an issue, check out my changes so we can push them upstream and to the wp plugins list as well.

**Comment by dominykasgel** [comment]
Nice! :) Your changes looks good! Thank you. Would you like to edit readme.txt and add yourself as a contributor? @joernroeder

**Comment by joernroeder** [comment]
@dominykasgel yeah sure! I had some other changes in mind to make it even more lightweight and a bit faster. For example embedding the svg source as template into the options instead of fetching it from the server to save an additional http request and caching some jQuery selectors is something i thought about.

I'll send another pull request with all my changes as soon as i finalized them. And yes, i'll add myself to the readme :) have a great weekend!

**Pull request closed without merging**
